In [2]:
import pandas as pd

In [111]:
file_path = "data/raw/england/era4_apr2024_may2026/March-2026-AE-by-provider-sJh4x.xls"

In [112]:
import os
print(os.path.exists(file_path))

True

In [113]:
df = pd.read_excel(file_path, sheet_name="Provider Level Data", engine="xlrd")

In [114]:
print(df.head(20))

    Unnamed: 0           Unnamed: 1  \
0          NaN               Title:
1          NaN                  NaN
2          NaN             Summary:
3          NaN                  NaN
4          NaN              Period:
5          NaN              Source:
6          NaN               Basis:
7          NaN           Published:
8          NaN             Revised:
9          NaN              Status:
10         NaN             Contact:
11         NaN                  NaN
12         NaN  Provider Level Data
13         NaN                  NaN
14         NaN                 Code
15         NaN                    -
16         NaN                  NaN
17         NaN                  RC9
18         NaN                  RGT
19         NaN                  RWH

                                           Unnamed: 2  \
0   A&E Attendances & Emergency Admission monthly ...
1                                                 NaN
2   The total of booked and non-booked A&E attenda...
3                                                 NaN
4                                          March 2026
5                       SDCS data collection - MSitAE
6                                            Provider
7                                     16th April 2026
8                                       14th May 2026
9                                           Published
10               Kerry Evert - england.aedata@nhs.net
11                                                NaN
12                                                NaN
13                                                NaN
14                                             Region
15                                                  -
16                                                NaN
17                       NHS England East Of England
18                       NHS England East Of England
19                       NHS England East Of England

                                           Unnamed: 3  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                               Name
15                                            England
16                                                NaN
17        Bedfordshire Hospitals NHS Foundation Trust
18  Cambridge University Hospitals NHS Foundation ...
19    East And North Hertfordshire Teaching NHS Trust

                                 4                                      5  \
0                                7                                      8
1                              NaN                                    NaN
2                              NaN                                    NaN
3                              NaN                                    NaN
4                              NaN                                    NaN
5                              NaN                                    NaN
6                              NaN                                    NaN
7                              NaN                                    NaN
8                              NaN                                    NaN
9                              NaN                                    NaN
10                             NaN                                    NaN
11                             NaN                                    NaN
12                             NaN                                    NaN
13                 A&E attendances                                    NaN
14  Type 1 Departments - Major A&E  Type 2 Departments - Single Specialty
15                         1478144                                  55393
16                             NaN                                    NaN
17                           17712                                      0
18                           12038                                      0
19                            9208                                      0

                                                   6         Unnamed: 7  \
0                                                  9                NaN
1                                                NaN                NaN
2                                                NaN                NaN
3                                                NaN                NaN
4                                                NaN                NaN
5                                                NaN                NaN
6                                                NaN                NaN
7                                                NaN                NaN
8                                                NaN                NaN
9                                                NaN                NaN
10                                               NaN                NaN
11                                               NaN                NaN
12                                               NaN                NaN
13                                               NaN                NaN
14  Type 3 Departments - Other A&E/Minor Injury Unit  Total attendances
15                                            898735            2432272
16                                               NaN                NaN
17                                              9389              27101
18                                              5929              17967
19                                              9068              18276

                                           Unnamed: 8  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13  A&E attendances less than 4 hours from arrival...
14                     Type 1 Departments - Major A&E
15                                             947365
16                                                NaN
17                                              12286
18                                               7034
19                                               4686

                               Unnamed: 9  ...  \
0                                     NaN  ...
1                                     NaN  ...
2                                     NaN  ...
3                                     NaN  ...
4                                     NaN  ...
5                                     NaN  ...
6                                     NaN  ...
7                                     NaN  ...
8                                     NaN  ...
9                                     NaN  ...
10                                    NaN  ...
11                                    NaN  ...
12                                    NaN  ...
13                                    NaN  ...
14  Type 2 Departments - Single Specialty  ...
15                                  53329  ...
16                                    NaN  ...
17                                      0  ...
18                                      0  ...
19                                      0  ...

                               Unnamed: 19  \
0                                      NaN
1                                      NaN
2                                      NaN
3                                      NaN
4                                      NaN
5                                      NaN
6                                      NaN
7                                      NaN
8                                      NaN
9                                      NaN
10                                     NaN
11                                     NaN
12                                     NaN
13                                     NaN
14  Percentage in 4 hours or less (type 3)
15                                0.973443
16                                     NaN
17                                       1
18                                0.979929
19                                0.989303

                                     18                                   19  \
0                                   NaN                                  NaN
1                                   NaN                                  NaN
2                                   NaN                                  NaN
3                                   NaN                                  NaN
4                                   NaN                                  NaN
5                                   NaN                                  NaN
6                                   NaN                                  NaN
7                                   NaN                                  NaN
8                                   NaN                                  NaN
9                                   NaN                                  NaN
10                                  NaN                                  NaN
11                                  NaN                                  NaN
12                                  NaN                                  NaN
13                 Emergency Admissions                                  NaN
14  Emergency Admissions via Type 1 A&E  Emergency Admissions via Type 2 A&E
15                               402356                                 1423
16                                  NaN                                  NaN
17                                 5351                                    0
18                                 2987                                    0
19                                 2396                                    0

                                           20  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
5                                         NaN
6                                         NaN
7                                         NaN
8                                         NaN
9                                         NaN
10                                        NaN
11                                        NaN
12                                        NaN
13                                        NaN
14  Emergency Admissions via Type 3 and 4 A&E
15                                       6226
16                                        NaN
17                                          0
18                                         36
19                                          2

                           Unnamed: 23  \
0                                  NaN
1                                  NaN
2                                  NaN
3                                  NaN
4                                  NaN
5                                  NaN
6                                  NaN
7                                  NaN
8                                  NaN
9                                  NaN
10                                 NaN
11                                 NaN
12                                 NaN
13                                 NaN
14  Total Emergency Admissions via A&E
15                              410005
16                                 NaN
17                                5351
18                                3023
19                                2398

                                              21                 Unnamed: 25  \
0                                            NaN                         NaN
1                                            NaN                         NaN
2                                            NaN                         NaN
3                                            NaN                         NaN
4                                            NaN                         NaN
5                                            NaN                         NaN
6                                            NaN                         NaN
7                                            NaN                         NaN
8                                            NaN                         NaN
9                                            NaN                         NaN
10                                           NaN                         NaN
11                                           NaN                         NaN
12                                           NaN                         NaN
13                                           NaN                         NaN
14  Other Emergency admissions (i.e not via A&E)  Total Emergency Admissions
15                                        143887                      553892
16                                           NaN                         NaN
17                                          2484                        7835
18                                           452                        3475
19                                           283                        2681

                                                   16  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14  Number of patients spending >4 hours from deci...
15                                             123870
16                                                NaN
17                                                 95
18                                                962
19                                                370

                                                   17  \
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14  Number of patients spending >12 hours from dec...
15                                              46665
16                                                NaN
17                                                 15
18                                                404
19                                                 65

                                          Unnamed: 28
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN
15                                                NaN
16                                                NaN
17  NHS Bedfordshire, Luton And Milton Keynes Inte...
18  NHS Cambridgeshire And Peterborough Integrated...
19  NHS Hertfordshire And West Essex Integrated Ca...

[20 rows x 29 columns]

In [115]:
df = pd.read_excel(
    file_path,
    sheet_name="Provider Level Data",
    engine="xlrd",
    skiprows=15
)
df.head(3)

,Unnamed: 0,Code,Region,Name,Type 1 Departments - Major A&E,Type 2 Departments - Single Specialty,Type 3 Departments - Other A&E/Minor Injury Unit,Total attendances,Type 1 Departments - Major A&E.1,Type 2 Departments - Single Specialty.1,...,Percentage in 4 hours or less (type 3),Emergency Admissions via Type 1 A&E,Emergency Admissions via Type 2 A&E,Emergency Admissions via Type 3 and 4 A&E,Total Emergency Admissions via A&E,Other Emergency admissions (i.e not via A&E),Total Emergency Admissions,Number of patients spending >4 hours from decision to admit to admission,Number of patients spending >12 hours from decision to admit to admission,Unnamed: 28
0,NaN,-,-,England,1478144.0,55393.0,898735.0,2432272.0,947365.0,53329.0,...,0.973443,402356.0,1423.0,6226.0,410005.0,143887.0,553892.0,123870.0,46665.0,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,RC9,NHS England East Of England,Bedfordshire Hospitals NHS Foundation Trust,17712.0,0.0,9389.0,27101.0,12286.0,0.0,...,1,5351.0,0.0,0.0,5351.0,2484.0,7835.0,95.0,15.0,"NHS Bedfordshire, Luton And Milton Keynes Inte..."

In [116]:
df.shape

(214, 29)

In [117]:
df.columns.tolist()

['Unnamed: 0',
 'Code',
 'Region',
 'Name',
 'Type 1 Departments - Major A&E',
 'Type 2 Departments - Single Specialty',
 'Type 3 Departments - Other A&E/Minor Injury Unit',
 'Total attendances',
 'Type 1 Departments - Major A&E.1',
 'Type 2 Departments - Single Specialty.1',
 'Type 3 Departments - Other A&E/Minor Injury Unit.1',
 'Total Attendances < 4 hours',
 'Type 1 Departments - Major A&E.2',
 'Type 2 Departments - Single Specialty.2',
 'Type 3 Departments - Other A&E/Minor Injury Unit.2',
 'Total Attendances > 4 hours',
 'Percentage in 4 hours or less (all)',
 'Percentage in 4 hours or less (type 1)',
 'Percentage in 4 hours or less (type 2)',
 'Percentage in 4 hours or less (type 3)',
 'Emergency Admissions via Type 1 A&E',
 'Emergency Admissions via Type 2 A&E',
 'Emergency Admissions via Type 3 and 4 A&E',
 'Total Emergency Admissions via A&E',
 'Other Emergency admissions (i.e not via A&E)',
 'Total Emergency Admissions',
 'Number of patients spending >4 hours from decision to admit to admission',
 'Number of patients spending >12 hours from decision to admit to admission',
 'Unnamed: 28']

In [118]:
df.Region.dtype

In [119]:
print(df.Region.dtype)

str

In [120]:
df.loc[3]

Unnamed: 0                                                                                                                 NaN
Code                                                                                                                       RGT
Region                                                                                            NHS England East Of England
Name                                                                         Cambridge University Hospitals NHS Foundation ...
Type 1 Departments - Major A&E                                                                                         12038.0
Type 2 Departments - Single Specialty                                                                                      0.0
Type 3 Departments - Other A&E/Minor Injury Unit                                                                        5929.0
Total attendances                                                                                                      17967.0
Type 1 Departments - Major A&E.1                                                                                        7034.0
Type 2 Departments - Single Specialty.1                                                                                    0.0
Type 3 Departments - Other A&E/Minor Injury Unit.1                                                                      5810.0
Total Attendances < 4 hours                                                                                            12844.0
Type 1 Departments - Major A&E.2                                                                                        5004.0
Type 2 Departments - Single Specialty.2                                                                                    0.0
Type 3 Departments - Other A&E/Minor Injury Unit.2                                                                       119.0
Total Attendances > 4 hours                                                                                             5123.0
Percentage in 4 hours or less (all)                                                                                   0.714866
Percentage in 4 hours or less (type 1)                                                                                0.584316
Percentage in 4 hours or less (type 2)                                                                                       -
Percentage in 4 hours or less (type 3)                                                                                0.979929
Emergency Admissions via Type 1 A&E                                                                                     2987.0
Emergency Admissions via Type 2 A&E                                                                                        0.0
Emergency Admissions via Type 3 and 4 A&E                                                                                 36.0
Total Emergency Admissions via A&E                                                                                      3023.0
Other Emergency admissions (i.e not via A&E)                                                                             452.0
Total Emergency Admissions                                                                                              3475.0
Number of patients spending >4 hours from decision to admit to admission                                                 962.0
Number of patients spending >12 hours from decision to admit to admission                                                404.0
Unnamed: 28                                                                  NHS Cambridgeshire And Peterborough Integrated...
Name: 3, dtype: object

In [121]:
df.loc[5]

Unnamed: 0                                                                                                                 NaN
Code                                                                                                                       RDE
Region                                                                                            NHS England East Of England
Name                                                                         East Suffolk And North Essex NHS Foundation Trust
Type 1 Departments - Major A&E                                                                                         11646.0
Type 2 Departments - Single Specialty                                                                                      0.0
Type 3 Departments - Other A&E/Minor Injury Unit                                                                       13538.0
Total attendances                                                                                                      25184.0
Type 1 Departments - Major A&E.1                                                                                        6626.0
Type 2 Departments - Single Specialty.1                                                                                    0.0
Type 3 Departments - Other A&E/Minor Injury Unit.1                                                                     12694.0
Total Attendances < 4 hours                                                                                            19320.0
Type 1 Departments - Major A&E.2                                                                                        5020.0
Type 2 Departments - Single Specialty.2                                                                                    0.0
Type 3 Departments - Other A&E/Minor Injury Unit.2                                                                       844.0
Total Attendances > 4 hours                                                                                             5864.0
Percentage in 4 hours or less (all)                                                                                   0.767154
Percentage in 4 hours or less (type 1)                                                                                0.568951
Percentage in 4 hours or less (type 2)                                                                                       -
Percentage in 4 hours or less (type 3)                                                                                0.937657
Emergency Admissions via Type 1 A&E                                                                                     5276.0
Emergency Admissions via Type 2 A&E                                                                                        0.0
Emergency Admissions via Type 3 and 4 A&E                                                                                  1.0
Total Emergency Admissions via A&E                                                                                      5277.0
Other Emergency admissions (i.e not via A&E)                                                                             294.0
Total Emergency Admissions                                                                                              5571.0
Number of patients spending >4 hours from decision to admit to admission                                                1431.0
Number of patients spending >12 hours from decision to admit to admission                                                548.0
Unnamed: 28                                                                  NHS Suffolk And North East Essex Integrated Ca...
Name: 5, dtype: object

In [122]:
df["Percentage in 4 hours or less (type 1)"].dtype

dtype('O')

In [123]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 29 columns):
 #   Column                                                                     Non-Null Count  Dtype
---  ------                                                                     --------------  -----
 0   Unnamed: 0                                                                 0 non-null      float64
 1   Code                                                                       200 non-null    str
 2   Region                                                                     200 non-null    str
 3   Name                                                                       200 non-null    str
 4   Type 1 Departments - Major A&E                                             200 non-null    float64
 5   Type 2 Departments - Single Specialty                                      200 non-null    float64
 6   Type 3 Departments - Other A&E/Minor Injury Unit                           200 non-null    float64
 7   Total attendances                                                          200 non-null    float64
 8   Type 1 Departments - Major A&E.1                                           200 non-null    float64
 9   Type 2 Departments - Single Specialty.1                                    200 non-null    float64
 10  Type 3 Departments - Other A&E/Minor Injury Unit.1                         200 non-null    float64
 11  Total Attendances < 4 hours                                                200 non-null    float64
 12  Type 1 Departments - Major A&E.2                                           200 non-null    float64
 13  Type 2 Departments - Single Specialty.2                                    200 non-null    float64
 14  Type 3 Departments - Other A&E/Minor Injury Unit.2                         200 non-null    float64
 15  Total Attendances > 4 hours                                                200 non-null    float64
 16  Percentage in 4 hours or less (all)                                        200 non-null    object
 17  Percentage in 4 hours or less (type 1)                                     200 non-null    object
 18  Percentage in 4 hours or less (type 2)                                     200 non-null    object
 19  Percentage in 4 hours or less (type 3)                                     200 non-null    object
 20  Emergency Admissions via Type 1 A&E                                        200 non-null    float64
 21  Emergency Admissions via Type 2 A&E                                        200 non-null    float64
 22  Emergency Admissions via Type 3 and 4 A&E                                  200 non-null    float64
 23  Total Emergency Admissions via A&E                                         200 non-null    float64
 24  Other Emergency admissions (i.e not via A&E)                               200 non-null    float64
 25  Total Emergency Admissions                                                 200 non-null    float64
 26  Number of patients spending >4 hours from decision to admit to admission   200 non-null    float64
 27  Number of patients spending >12 hours from decision to admit to admission  200 non-null    float64
 28  Unnamed: 28                                                                199 non-null    str
dtypes: float64(21), object(4), str(4)
memory usage: 48.6+ KB

In [124]:
df.isnull().sum()

Unnamed: 0                                                                   214
Code                                                                          14
Region                                                                        14
Name                                                                          14
Type 1 Departments - Major A&E                                                14
Type 2 Departments - Single Specialty                                         14
Type 3 Departments - Other A&E/Minor Injury Unit                              14
Total attendances                                                             14
Type 1 Departments - Major A&E.1                                              14
Type 2 Departments - Single Specialty.1                                       14
Type 3 Departments - Other A&E/Minor Injury Unit.1                            14
Total Attendances < 4 hours                                                   14
Type 1 Departments - Major A&E.2                                              14
Type 2 Departments - Single Specialty.2                                       14
Type 3 Departments - Other A&E/Minor Injury Unit.2                            14
Total Attendances > 4 hours                                                   14
Percentage in 4 hours or less (all)                                           14
Percentage in 4 hours or less (type 1)                                        14
Percentage in 4 hours or less (type 2)                                        14
Percentage in 4 hours or less (type 3)                                        14
Emergency Admissions via Type 1 A&E                                           14
Emergency Admissions via Type 2 A&E                                           14
Emergency Admissions via Type 3 and 4 A&E                                     14
Total Emergency Admissions via A&E                                            14
Other Emergency admissions (i.e not via A&E)                                  14
Total Emergency Admissions                                                    14
Number of patients spending >4 hours from decision to admit to admission      14
Number of patients spending >12 hours from decision to admit to admission     14
Unnamed: 28                                                                   15
dtype: int64

In [125]:
df[df.index.isin(range(2,12))]

,Unnamed: 0,Code,Region,Name,Type 1 Departments - Major A&E,Type 2 Departments - Single Specialty,Type 3 Departments - Other A&E/Minor Injury Unit,Total attendances,Type 1 Departments - Major A&E.1,Type 2 Departments - Single Specialty.1,...,Percentage in 4 hours or less (type 3),Emergency Admissions via Type 1 A&E,Emergency Admissions via Type 2 A&E,Emergency Admissions via Type 3 and 4 A&E,Total Emergency Admissions via A&E,Other Emergency admissions (i.e not via A&E),Total Emergency Admissions,Number of patients spending >4 hours from decision to admit to admission,Number of patients spending >12 hours from decision to admit to admission,Unnamed: 28
2,NaN,RC9,NHS England East Of England,Bedfordshire Hospitals NHS Foundation Trust,17712.0,0.0,9389.0,27101.0,12286.0,0.0,...,1,5351.0,0.0,0.0,5351.0,2484.0,7835.0,95.0,15.0,"NHS Bedfordshire, Luton And Milton Keynes Inte..."
3,NaN,RGT,NHS England East Of England,Cambridge University Hospitals NHS Foundation ...,12038.0,0.0,5929.0,17967.0,7034.0,0.0,...,0.979929,2987.0,0.0,36.0,3023.0,452.0,3475.0,962.0,404.0,NHS Cambridgeshire And Peterborough Integrated...
4,NaN,RWH,NHS England East Of England,East And North Hertfordshire Teaching NHS Trust,9208.0,0.0,9068.0,18276.0,4686.0,0.0,...,0.989303,2396.0,0.0,2.0,2398.0,283.0,2681.0,370.0,65.0,NHS Hertfordshire And West Essex Integrated Ca...
5,NaN,RDE,NHS England East Of England,East Suffolk And North Essex NHS Foundation Trust,11646.0,0.0,13538.0,25184.0,6626.0,0.0,...,0.937657,5276.0,0.0,1.0,5277.0,294.0,5571.0,1431.0,548.0,NHS Suffolk And North East Essex Integrated Ca...
6,NaN,RY4,NHS England East Of England,Hertfordshire Community NHS Trust,0.0,0.0,1223.0,1223.0,0.0,0.0,...,0.968929,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NHS Hertfordshire And West Essex Integrated Ca...
7,NaN,DT301,NHS England East Of England,Herts Urgent Care (Ascots Lane),0.0,0.0,2144.0,2144.0,0.0,0.0,...,0.948694,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NHS Hertfordshire And West Essex Integrated Ca...
8,NaN,RGP,NHS England East Of England,James Paget University Hospitals NHS Foundatio...,7717.0,0.0,1655.0,9372.0,5039.0,0.0,...,1,1586.0,0.0,0.0,1586.0,530.0,2116.0,906.0,427.0,NHS Norfolk And Waveney Integrated Care Board
9,NaN,RAJ,NHS England East Of England,Mid And South Essex NHS Foundation Trust,28524.0,0.0,8415.0,36939.0,17065.0,0.0,...,0.959239,8908.0,0.0,125.0,9033.0,1270.0,10303.0,3130.0,793.0,NHS Mid And South Essex Integrated Care Board
10,NaN,RD8,NHS England East Of England,Milton Keynes University Hospital NHS Foundati...,9104.0,0.0,5943.0,15047.0,6089.0,0.0,...,0.984351,2603.0,0.0,0.0,2603.0,454.0,3057.0,603.0,0.0,"NHS Bedfordshire, Luton And Milton Keynes Inte..."
11,NaN,RM1,NHS England East Of England,Norfolk And Norwich University Hospitals NHS F...,13490.0,0.0,7873.0,21363.0,9864.0,0.0,...,0.998603,2256.0,0.0,0.0,2256.0,1575.0,3831.0,864.0,261.0,NHS Norfolk And Waveney Integrated Care Board

In [126]:
df[['Name',
 'Type 1 Departments - Major A&E',
 'Type 1 Departments - Major A&E.1',
 'Type 1 Departments - Major A&E.2',
 'Percentage in 4 hours or less (type 1)',
 'Emergency Admissions via Type 1 A&E',
 'Total Emergency Admissions',
 'Number of patients spending >12 hours from decision to admit to admission']].loc[2:12]

,Name,Type 1 Departments - Major A&E,Type 1 Departments - Major A&E.1,Type 1 Departments - Major A&E.2,Percentage in 4 hours or less (type 1),Emergency Admissions via Type 1 A&E,Total Emergency Admissions,Number of patients spending >12 hours from decision to admit to admission
2,Bedfordshire Hospitals NHS Foundation Trust,17712.0,12286.0,5426.0,0.693654,5351.0,7835.0,15.0
3,Cambridge University Hospitals NHS Foundation ...,12038.0,7034.0,5004.0,0.584316,2987.0,3475.0,404.0
4,East And North Hertfordshire Teaching NHS Trust,9208.0,4686.0,4522.0,0.508905,2396.0,2681.0,65.0
5,East Suffolk And North Essex NHS Foundation Trust,11646.0,6626.0,5020.0,0.568951,5276.0,5571.0,548.0
6,Hertfordshire Community NHS Trust,0.0,0.0,0.0,-,0.0,0.0,0.0
7,Herts Urgent Care (Ascots Lane),0.0,0.0,0.0,-,0.0,0.0,0.0
8,James Paget University Hospitals NHS Foundatio...,7717.0,5039.0,2678.0,0.652974,1586.0,2116.0,427.0
9,Mid And South Essex NHS Foundation Trust,28524.0,17065.0,11459.0,0.598268,8908.0,10303.0,793.0
10,Milton Keynes University Hospital NHS Foundati...,9104.0,6089.0,3015.0,0.668827,2603.0,3057.0,0.0
11,Norfolk And Norwich University Hospitals NHS F...,13490.0,9864.0,3626.0,0.731208,2256.0,3831.0,261.0
12,North West Anglia NHS Foundation Trust,16126.0,10304.0,5822.0,0.638968,4176.0,5646.0,945.0

In [127]:
df.columns.tolist()

['Unnamed: 0',
 'Code',
 'Region',
 'Name',
 'Type 1 Departments - Major A&E',
 'Type 2 Departments - Single Specialty',
 'Type 3 Departments - Other A&E/Minor Injury Unit',
 'Total attendances',
 'Type 1 Departments - Major A&E.1',
 'Type 2 Departments - Single Specialty.1',
 'Type 3 Departments - Other A&E/Minor Injury Unit.1',
 'Total Attendances < 4 hours',
 'Type 1 Departments - Major A&E.2',
 'Type 2 Departments - Single Specialty.2',
 'Type 3 Departments - Other A&E/Minor Injury Unit.2',
 'Total Attendances > 4 hours',
 'Percentage in 4 hours or less (all)',
 'Percentage in 4 hours or less (type 1)',
 'Percentage in 4 hours or less (type 2)',
 'Percentage in 4 hours or less (type 3)',
 'Emergency Admissions via Type 1 A&E',
 'Emergency Admissions via Type 2 A&E',
 'Emergency Admissions via Type 3 and 4 A&E',
 'Total Emergency Admissions via A&E',
 'Other Emergency admissions (i.e not via A&E)',
 'Total Emergency Admissions',
 'Number of patients spending >4 hours from decision to admit to admission',
 'Number of patients spending >12 hours from decision to admit to admission',
 'Unnamed: 28']

In [128]:
keep_columns = [
    "Code",
    "Region",
    "Name",
    'Type 1 Departments - Major A&E',
    'Type 1 Departments - Major A&E.2',
    'Percentage in 4 hours or less (type 1)',
    'Emergency Admissions via Type 1 A&E',
    'Total Emergency Admissions',
    'Number of patients spending >12 hours from decision to admit to admission',
]

In [129]:
df = df[keep_columns]

In [130]:
df = df.rename(columns={
    "Code": "trust_code",
    "Region": "trust_region",
    "Name": "trust_name",
    "Type 1 Departments - Major A&E": "attendances_type1",
    "Type 1 Departments - Major A&E.2": "breaches_4hr_type1",
    "Percentage in 4 hours or less (type 1)": "pct_4hr_type1",
    "Number of patients spending >12 hours from decision to admit to admission": "waits_12hr",
    "Emergency Admissions via Type 1 A&E": "admissions_type1",
    "Total Emergency Admissions": "total_admissions"
})

In [131]:
df.head(3)

,trust_code,trust_region,trust_name,attendances_type1,breaches_4hr_type1,pct_4hr_type1,admissions_type1,total_admissions,waits_12hr
0,-,-,England,1478144.0,530779.0,0.640915,402356.0,553892.0,46665.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,RC9,NHS England East Of England,Bedfordshire Hospitals NHS Foundation Trust,17712.0,5426.0,0.693654,5351.0,7835.0,15.0

In [132]:
# Drop the England total row AND the blank spacer row in one go
df = df[df["trust_code"].notna() & (df["trust_code"] != "-")]

In [133]:
df.shape

(199, 9)

In [134]:
df.head(5)

,trust_code,trust_region,trust_name,attendances_type1,breaches_4hr_type1,pct_4hr_type1,admissions_type1,total_admissions,waits_12hr
2,RC9,NHS England East Of England,Bedfordshire Hospitals NHS Foundation Trust,17712.0,5426.0,0.693654,5351.0,7835.0,15.0
3,RGT,NHS England East Of England,Cambridge University Hospitals NHS Foundation ...,12038.0,5004.0,0.584316,2987.0,3475.0,404.0
4,RWH,NHS England East Of England,East And North Hertfordshire Teaching NHS Trust,9208.0,4522.0,0.508905,2396.0,2681.0,65.0
5,RDE,NHS England East Of England,East Suffolk And North Essex NHS Foundation Trust,11646.0,5020.0,0.568951,5276.0,5571.0,548.0
6,RY4,NHS England East Of England,Hertfordshire Community NHS Trust,0.0,0.0,-,0.0,0.0,0.0

In [135]:
# Keeping only trusts that actually have Type 1 A&E
df = df[df["attendances_type1"] > 0]

In [136]:
df.info()

<class 'pandas.DataFrame'>
Index: 121 entries, 2 to 200
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   trust_code          121 non-null    str
 1   trust_region        121 non-null    str
 2   trust_name          121 non-null    str
 3   attendances_type1   121 non-null    float64
 4   breaches_4hr_type1  121 non-null    float64
 5   pct_4hr_type1       121 non-null    object
 6   admissions_type1    121 non-null    float64
 7   total_admissions    121 non-null    float64
 8   waits_12hr          121 non-null    float64
dtypes: float64(5), object(1), str(3)
memory usage: 9.5+ KB

In [137]:
numeric_cols = [
    "attendances_type1",
    "breaches_4hr_type1",
    "pct_4hr_type1",
    "admissions_type1",
    "total_admissions",
    "waits_12hr"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [138]:
df.info()

<class 'pandas.DataFrame'>
Index: 121 entries, 2 to 200
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   trust_code          121 non-null    str
 1   trust_region        121 non-null    str
 2   trust_name          121 non-null    str
 3   attendances_type1   121 non-null    float64
 4   breaches_4hr_type1  121 non-null    float64
 5   pct_4hr_type1       121 non-null    float64
 6   admissions_type1    121 non-null    float64
 7   total_admissions    121 non-null    float64
 8   waits_12hr          121 non-null    float64
dtypes: float64(6), str(3)
memory usage: 9.5 KB

In [139]:
df.shape

(121, 9)

In [140]:
df["period"]="2026-05"

In [141]:
df.head()

,trust_code,trust_region,trust_name,attendances_type1,breaches_4hr_type1,pct_4hr_type1,admissions_type1,total_admissions,waits_12hr,period
2,RC9,NHS England East Of England,Bedfordshire Hospitals NHS Foundation Trust,17712.0,5426.0,0.693654,5351.0,7835.0,15.0,2026-05
3,RGT,NHS England East Of England,Cambridge University Hospitals NHS Foundation ...,12038.0,5004.0,0.584316,2987.0,3475.0,404.0,2026-05
4,RWH,NHS England East Of England,East And North Hertfordshire Teaching NHS Trust,9208.0,4522.0,0.508905,2396.0,2681.0,65.0,2026-05
5,RDE,NHS England East Of England,East Suffolk And North Essex NHS Foundation Trust,11646.0,5020.0,0.568951,5276.0,5571.0,548.0,2026-05
8,RGP,NHS England East Of England,James Paget University Hospitals NHS Foundatio...,7717.0,2678.0,0.652974,1586.0,2116.0,427.0,2026-05

In [142]:
df.info()

<class 'pandas.DataFrame'>
Index: 121 entries, 2 to 200
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   trust_code          121 non-null    str
 1   trust_region        121 non-null    str
 2   trust_name          121 non-null    str
 3   attendances_type1   121 non-null    float64
 4   breaches_4hr_type1  121 non-null    float64
 5   pct_4hr_type1       121 non-null    float64
 6   admissions_type1    121 non-null    float64
 7   total_admissions    121 non-null    float64
 8   waits_12hr          121 non-null    float64
 9   period              121 non-null    str
dtypes: float64(6), str(4)
memory usage: 10.4 KB

In [143]:
df["period"] = pd.to_datetime("2026-05-01")
df.head()
df.dtypes

trust_code                       str
trust_region                     str
trust_name                       str
attendances_type1            float64
breaches_4hr_type1           float64
pct_4hr_type1                float64
admissions_type1             float64
total_admissions             float64
waits_12hr                   float64
period                datetime64[us]
dtype: object

In [144]:
def load_england_ae_file(file_path, period_date):
    """
    Load and clean one NHS England monthly A&E file.
    Handles both legacy .xls and modern .xlsx files (regardless of extension).
    """
    
    # Detect the actual file format from the first bytes
    with open(file_path, "rb") as f:
        first_bytes = f.read(8)
    
    if first_bytes[:2] == b"PK":
        # XLSX (zip-based)
        engine = "openpyxl"
    elif first_bytes[:4] == b"\xd0\xcf\x11\xe0":
        # Legacy XLS
        engine = "xlrd"
    else:
        raise ValueError(f"Unknown file format in {file_path}")
    
    # Safety check: does the expected sheet exist?
    xl = pd.ExcelFile(file_path, engine=engine)
    if "Provider Level Data" not in xl.sheet_names:
        raise ValueError(
            f"'Provider Level Data' sheet not found in {file_path}. "
            f"Sheets found: {xl.sheet_names}"
        )
    
    # Read the file
    df = pd.read_excel(
        file_path,
        sheet_name="Provider Level Data",
        engine=engine,
        skiprows=15
    )
    
    # Safety check 2: do the expected columns exist?
    required_cols = [
        "Code",
        "Region",
        "Name",
        "Type 1 Departments - Major A&E",
        "Type 1 Departments - Major A&E.2",
        "Percentage in 4 hours or less (type 1)",
        "Number of patients spending >12 hours from decision to admit to admission",
        "Emergency Admissions via Type 1 A&E",
        "Total Emergency Admissions"
    ]
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        raise ValueError(
            f"Missing expected columns in {file_path}: {missing}"
        )
    
    # Step 2 — Keep & rename
    df = df[required_cols].rename(columns={
        "Code": "trust_code",
        "Region": "trust_region",
        "Name": "trust_name",
        "Type 1 Departments - Major A&E": "attendances_type1",
        "Type 1 Departments - Major A&E.2": "breaches_4hr_type1",
        "Percentage in 4 hours or less (type 1)": "pct_4hr_type1",
        "Number of patients spending >12 hours from decision to admit to admission": "waits_12hr",
        "Emergency Admissions via Type 1 A&E": "admissions_type1",
        "Total Emergency Admissions": "total_admissions"
    })
    
    # Step 3 — Filter junk rows
    df = df[df["trust_code"].notna() & (df["trust_code"] != "-")]
    
    # Step 4 — Convert numeric columns
    numeric_cols = [
        "attendances_type1", "breaches_4hr_type1", "pct_4hr_type1",
        "admissions_type1", "total_admissions", "waits_12hr"
    ]
    for col in numeric_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    
    # Step 5 — Filter non-Type-1 trusts
    df = df[df["attendances_type1"] > 0]
    
    # Step 6 — Add period
    df["period"] = pd.to_datetime(period_date)
    
    # Safety check 3: did we get a sensible number of trusts?
    if len(df) < 50:
        print(
            f"⚠ Warning: only {len(df)} trusts in {file_path} — "
            f"may indicate a structure issue"
        )
    
    return df

In [145]:
df_may26 = load_england_ae_file(
    file_path="data/raw/england/era4_apr2024_may2026/May-26-AE-by-provider-QVPHP.xls",
    period_date="2026-05-01"
)

df_may26.head()

,trust_code,trust_region,trust_name,attendances_type1,breaches_4hr_type1,pct_4hr_type1,waits_12hr,admissions_type1,total_admissions,period
2,RC9,NHS England East Of England,Bedfordshire Hospitals NHS Foundation Trust,18436.0,6598.0,0.642113,43.0,5237.0,7389.0,2026-05-01
3,RGT,NHS England East Of England,Cambridge University Hospitals NHS Foundation ...,12024.0,5598.0,0.534431,518.0,2749.0,3247.0,2026-05-01
4,RWH,NHS England East Of England,East And North Hertfordshire Teaching NHS Trust,9263.0,4617.0,0.501565,158.0,2269.0,2704.0,2026-05-01
5,RDE,NHS England East Of England,East Suffolk And North Essex NHS Foundation Trust,11914.0,4727.0,0.603240,511.0,5112.0,5350.0,2026-05-01
8,RGP,NHS England East Of England,James Paget University Hospitals NHS Foundatio...,8220.0,2813.0,0.657786,281.0,1696.0,2216.0,2026-05-01

In [146]:
df_may26.info()

<class 'pandas.DataFrame'>
Index: 121 entries, 2 to 193
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   trust_code          121 non-null    str
 1   trust_region        121 non-null    str
 2   trust_name          121 non-null    str
 3   attendances_type1   121 non-null    float64
 4   breaches_4hr_type1  121 non-null    float64
 5   pct_4hr_type1       121 non-null    float64
 6   waits_12hr          121 non-null    float64
 7   admissions_type1    121 non-null    float64
 8   total_admissions    121 non-null    float64
 9   period              121 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(6), str(3)
memory usage: 10.4 KB

In [147]:
from pathlib import Path

era4_folder = Path("data/raw/england/era4_apr2024_may2026")

# List all .xls files in this folder
era4_files = list(era4_folder.glob("*.xls"))
print(f"Found {len(era4_files)} files")
for f in era4_files[:5]:
    print(f" - {f.name}")

Found 26 files
 - April-2024-AE-by-provider-24y7F-revised.xls
 - April-2025-AE-by-provider-sfo2q-revised.xls
 - April-26-AE-by-provider-v2-tKVXL.xls
 - August-2024-AE-by-provider-A4au3-1.xls
 - August-2025-AE-by-provider-0G7Wh-revised-v2-1.xls

In [148]:
import re
from datetime import datetime

def extract_period_from_filename(filename):
    """
    Pull the reporting period out of an NHS filename.
    Handles both 'April-2024-AE-...' and 'April-26-AE-...' patterns.
    Returns a date string like '2024-04-01'.
    """
    months = {
        "january":1, "february":2, "march":3, "april":4, "may":5, "june":6,
        "july":7, "august":8, "september":9, "october":10, "november":11, "december":12
    }
    
    name = filename.lower()
    
    # Find month name
    month_num = None
    for m_name, m_num in months.items():
        if m_name in name:
            month_num = m_num
            break
    
    if month_num is None:
        raise ValueError(f"Could not find month name in {filename}")
    
    # Find year — try 4-digit first, then 2-digit
    year_match = re.search(r"(20\d{2})", name)
    if year_match:
        year = int(year_match.group(1))
    else:
        # Try 2-digit year like '-26-' or '-24-'
        year_match = re.search(r"-(\d{2})-", name)
        if year_match:
            year = 2000 + int(year_match.group(1))
        else:
            raise ValueError(f"Could not find year in {filename}")
    
    return f"{year}-{month_num:02d}-01"

In [149]:
for f in era4_files[:5]:
    period = extract_period_from_filename(f.name)
    print(f"{f.name} → {period}")

April-2024-AE-by-provider-24y7F-revised.xls → 2024-04-01
April-2025-AE-by-provider-sfo2q-revised.xls → 2025-04-01
April-26-AE-by-provider-v2-tKVXL.xls → 2026-04-01
August-2024-AE-by-provider-A4au3-1.xls → 2024-08-01
August-2025-AE-by-provider-0G7Wh-revised-v2-1.xls → 2025-08-01

In [150]:
all_dataframes = []
failed_files = []

for file_path in era4_files:
    try:
        period = extract_period_from_filename(file_path.name)
        df_one = load_england_ae_file(str(file_path), period)
        all_dataframes.append(df_one)
        print(f"✓ {file_path.name} → {len(df_one)} trusts")
    except Exception as e:
        failed_files.append((file_path.name, str(e)))
        print(f"✗ {file_path.name} FAILED: {e}")

# Combine all successfully read files into one dataframe
era4_combined = pd.concat(all_dataframes, ignore_index=True)

print(f"\nTotal rows: {len(era4_combined)}")
print(f"Successful files: {len(all_dataframes)}")
print(f"Failed files: {len(failed_files)}")

✓ April-2024-AE-by-provider-24y7F-revised.xls → 122 trusts
✓ April-2025-AE-by-provider-sfo2q-revised.xls → 121 trusts
✓ April-26-AE-by-provider-v2-tKVXL.xls → 121 trusts
✓ August-2024-AE-by-provider-A4au3-1.xls → 122 trusts
✓ August-2025-AE-by-provider-0G7Wh-revised-v2-1.xls → 121 trusts
✓ December-2024-AE-by-provider-28BHd.xls → 122 trusts
✓ December-2025-AE-by-provider-revised-F5epgl.xls → 121 trusts
✓ February-2025-AE-by-provider-WLBzp-revised.xls → 121 trusts
✓ February-2026-AE-by-provider-lopYX.xls → 121 trusts
✓ January-2025-AE-by-provider-HyTsU.xls → 121 trusts
✓ July-2024-AE-by-provider-2odvB-revised.xls → 122 trusts
✓ July-2025-AE-by-provider-iX1Zj-revised.xls → 121 trusts
✓ June-2024-AE-by-provider-HW3bJ.xls → 122 trusts
✓ June-2025-AE-by-provider-CkkTE-revised.xls → 121 trusts
✓ March-2025-AE-by-provider-cAki3.xls → 121 trusts
✓ March-2026-AE-by-provider-sJh4x.xls → 121 trusts
✓ May-2024-AE-by-provider-uPWkU-1.xls → 122 trusts
✓ May-2025-AE-by-provider-RIgsW-revised.xls → 121 trusts
✓ May-26-AE-by-provider-QVPHP.xls → 121 trusts
✓ Monthly-AE-January-2026-Provider-revised-lqb32.xls → 121 trusts
✓ November-2024-AE-by-provider-XEZnh-revised-1.xls → 122 trusts
✓ November-2025-AE-by-provider-revised-98BKJ.xls → 121 trusts
✓ October-2024-AE-by-provider-gAzJa-revised.xls → 122 trusts
✓ October-2025-AE-by-provider-XzO71.xls → 121 trusts
✓ September-2024-AE-by-provider-t42ve.xls → 122 trusts
✓ September-2025-AE-by-provider-eEVFy-revised.xls → 121 trusts

Total rows: 3155
Successful files: 26
Failed files: 0

In [151]:
# All 4 era folders
era_folders = [
    Path("data/raw/england/era1_apr2019_mar2020"),
    Path("data/raw/england/era2_apr2020_mar2022"),
    Path("data/raw/england/era3_apr2022_mar2024"),
    Path("data/raw/england/era4_apr2024_may2026"),
]

all_dataframes = []
failed_files = []

for folder in era_folders:
    print(f"\n--- Processing {folder.name} ---")
    files = list(folder.glob("*.xls")) + list(folder.glob("*.xlsx"))
    
    for file_path in files:
        try:
            period = extract_period_from_filename(file_path.name)
            df_one = load_england_ae_file(str(file_path), period)
            all_dataframes.append(df_one)
            print(f"✓ {file_path.name} → {len(df_one)} trusts")
        except Exception as e:
            failed_files.append((file_path.name, str(type(e).__name__), str(e)))
            print(f"✗ {file_path.name} FAILED: {type(e).__name__}: {e}")

# Combine
england_all = pd.concat(all_dataframes, ignore_index=True)

print(f"\n=== SUMMARY ===")
print(f"Total rows: {len(england_all)}")
print(f"Successful files: {len(all_dataframes)}")
print(f"Failed files: {len(failed_files)}")
print(f"Date range: {england_all['period'].min()} to {england_all['period'].max()}")
print(f"Unique periods: {england_all['period'].nunique()}")

--- Processing era1_apr2019_mar2020 ---
✓ Monthly-AE-April-2019-revised-220720-632O5.xls → 133 trusts
✓ Monthly-AE-August-2019-revised-210720-N29U9.xls → 133 trusts
✓ Monthly-AE-December-2019-revised-220720-7h43F.xls → 132 trusts
✓ Monthly-AE-February-2020-revised-280720-TR4gv.xls → 132 trusts
✓ Monthly-AE-January-2020-revised-220720-9EPnl.xls → 132 trusts
✓ Monthly-AE-July-2019-revised-210720-0Xmt8.xls → 133 trusts
✓ Monthly-AE-June-2019-revised-210720-n48F9.xls → 133 trusts
✓ Monthly-AE-March-2020-revised-220720-p4H66-1.xls → 132 trusts
✓ Monthly-AE-May-2019-revised-220720-3o2Nl.xls → 133 trusts
✓ Monthly-AE-November-2019-revised-220720-HbJQ1.xls → 132 trusts
✓ Monthly-October-2019-revised-210720-qm5hG.xls → 132 trusts
✓ Monthly-September-2019-revised-210720-L48uy.xls → 133 trusts

--- Processing era2_apr2020_mar2022 ---
✓ April-2020-AE-by-provider-revised-260421-M70yN.xls → 128 trusts
✓ April-2021-AE-by-provider-Q773u.xls → 126 trusts
✓ August-2020-AE-by-provider-revised-280421-7V9QM.xls → 128 trusts
✓ August-2021-AE-by-provider-Gi5Fh.xls → 126 trusts
✓ December-2020-AE-by-provider-revised-270421-eT4OL.xls → 127 trusts
✓ December-2021-AE-by-provider-oNwWs.xls → 125 trusts
✓ February-2021-AE-by-provider-revised-280421-EJ9nR.xls → 127 trusts
✓ February-2022-AE-by-provider-YgdXY.xls → 125 trusts
✓ January-2021-AE-by-provider-revised-280421-4OYWC.xls → 127 trusts
✓ January-2022-AE-by-provider-Xr900.xls → 125 trusts
✓ July-2020-AE-by-provider-YVQFD-revised-270421.xls → 128 trusts
✓ July-2021-AE-by-provider-8F7aS.xls → 126 trusts
✓ June-2020-AE-by-provider-revised-260421-9HrqH.xls → 128 trusts
✓ June-2021-AE-by-provider-2Qavs.xls → 126 trusts
✓ March-2021-AE-by-provider-revised-280421-7m0iV.xls → 127 trusts
✓ March-2022-AE-by-provider-1SaO5.xls → 125 trusts
✓ May-2020-AE-by-provider-revised-260421-qlSY5.xls → 128 trusts
✓ May-2021-AE-by-provider-R85f2.xls → 126 trusts
✓ November-2020-AE-by-provider-revised-270421-IOUCw.xls → 127 trusts
✓ November-2021-AE-by-provider-TO65c.xls → 125 trusts
✓ October-2020-AE-by-provider-revised-270421-9U2tp.xls → 127 trusts
✓ October-2021-AE-by-provider-0gyL5.xls → 125 trusts
✓ September-2020-AE-by-provider-revised-280421-6f9Yl.xls → 128 trusts
✓ September-2021-AE-by-provider-jDbjZ.xls → 126 trusts

--- Processing era3_apr2022_mar2024 ---
✓ April-2022-AE-revised-130624-by-provider-YVj1E.xls → 124 trusts
✓ April-2023-AE-revised-130624-by-provider-J1F7n.xls → 123 trusts
✓ August-2022-AE-by-provider-revised-110523-1Gqhs.xls → 124 trusts
✓ August-2023-AE-revised-130624-by-provider-FI80O-1.xls → 122 trusts
✓ December-2022-AE-by-provider-UScya-revised-110523.xls → 124 trusts
✓ December-2023-revised-130624-AE-by-provider-A3NaZ-1.xls → 122 trusts
✓ February-2023-AE-by-provider-Bu31G-revised-110523.xls → 124 trusts
✓ February-2024-AE-revised-130624-by-provider-kL472-1.xls → 122 trusts
✓ January-2023-AE-by-provider-9wvXO-revised-110523.xls → 124 trusts
✓ January-2024-AE-revised-130624-by-provider-4qYV2-1.xls → 122 trusts
✓ July-2022-AE-by-provider-revised-110523-Rr6Df.xls → 124 trusts
✓ July-2023-AE-revised-130624-by-provider-Z9pVf-1.xls → 122 trusts
✓ June-2022-AE-by-provider-dfTKt-revised-110523.xls → 124 trusts
✓ June-2023-AE-revised-130624-by-provider-5Uq9C-1.xls → 123 trusts
✓ March-2023-AE-by-provider-D6Ni9-revised-110523.xls → 124 trusts
✓ March-2024-AE-revised-by-provider-dmurT.xls → 122 trusts
✓ May-2022-AE-by-provider-revised-110523-OZPOx.xls → 124 trusts
✓ May-2023-AE-revised-130624-by-provider-jn7Oy.xls → 123 trusts
✓ November-2022-AE-by-provider-WINN6.xls → 124 trusts
✓ November-2023-AE-revised-130624-by-provider-3SOeF-1.xls → 122 trusts
✓ October-2022-AE-by-provider-vM3Lm-revised-110523.xls → 124 trusts
✓ October-2023-AE-revised-130624-by-provider-x6p9K-1.xls → 122 trusts
✓ September-2022-AE-by-provider-lT54V-revised-110523.xls → 124 trusts
✓ September-2023-AE-revised-130624-by-provider-0W4r0-1.xls → 122 trusts

--- Processing era4_apr2024_may2026 ---
✓ April-2024-AE-by-provider-24y7F-revised.xls → 122 trusts
✓ April-2025-AE-by-provider-sfo2q-revised.xls → 121 trusts
✓ April-26-AE-by-provider-v2-tKVXL.xls → 121 trusts
✓ August-2024-AE-by-provider-A4au3-1.xls → 122 trusts
✓ August-2025-AE-by-provider-0G7Wh-revised-v2-1.xls → 121 trusts
✓ December-2024-AE-by-provider-28BHd.xls → 122 trusts
✓ December-2025-AE-by-provider-revised-F5epgl.xls → 121 trusts
✓ February-2025-AE-by-provider-WLBzp-revised.xls → 121 trusts
✓ February-2026-AE-by-provider-lopYX.xls → 121 trusts
✓ January-2025-AE-by-provider-HyTsU.xls → 121 trusts
✓ July-2024-AE-by-provider-2odvB-revised.xls → 122 trusts
✓ July-2025-AE-by-provider-iX1Zj-revised.xls → 121 trusts
✓ June-2024-AE-by-provider-HW3bJ.xls → 122 trusts
✓ June-2025-AE-by-provider-CkkTE-revised.xls → 121 trusts
✓ March-2025-AE-by-provider-cAki3.xls → 121 trusts
✓ March-2026-AE-by-provider-sJh4x.xls → 121 trusts
✓ May-2024-AE-by-provider-uPWkU-1.xls → 122 trusts
✓ May-2025-AE-by-provider-RIgsW-revised.xls → 121 trusts
✓ May-26-AE-by-provider-QVPHP.xls → 121 trusts
✓ Monthly-AE-January-2026-Provider-revised-lqb32.xls → 121 trusts
✓ November-2024-AE-by-provider-XEZnh-revised-1.xls → 122 trusts
✓ November-2025-AE-by-provider-revised-98BKJ.xls → 121 trusts
✓ October-2024-AE-by-provider-gAzJa-revised.xls → 122 trusts
✓ October-2025-AE-by-provider-XzO71.xls → 121 trusts
✓ September-2024-AE-by-provider-t42ve.xls → 122 trusts
✓ September-2025-AE-by-provider-eEVFy-revised.xls → 121 trusts

=== SUMMARY ===
Total rows: 10736
Successful files: 86
Failed files: 0
Date range: 2019-04-01 00:00:00 to 2026-05-01 00:00:00
Unique periods: 86

In [152]:
print(f"Total files attempted: {len(all_dataframes) + len(failed_files)}")
print(f"Successful: {len(all_dataframes)}")
print(f"Failed: {len(failed_files)}")
print()
print("=== FAILED FILES ===")
for fname, err_type, err_msg in failed_files:
    print(f"\n{fname}")
    print(f"  Error: {err_type}: {err_msg}")

Total files attempted: 86
Successful: 86
Failed: 0

=== FAILED FILES ===

In [153]:
for folder in era_folders:
    count = len(list(folder.glob("*.xls")) + list(folder.glob("*.xlsx")))
    expected = {"era1_apr2019_mar2020": 12, "era2_apr2020_mar2022": 24, 
                "era3_apr2022_mar2024": 24, "era4_apr2024_may2026": 26}
    expected_count = expected.get(folder.name, "?")
    status = "✓" if count == expected_count else "✗"
    print(f"{status} {folder.name}: {count} files (expected {expected_count})")

✓ era1_apr2019_mar2020: 12 files (expected 12)
✓ era2_apr2020_mar2022: 24 files (expected 24)
✓ era3_apr2022_mar2024: 24 files (expected 24)
✓ era4_apr2024_may2026: 26 files (expected 26)

In [154]:
print(f"Total rows: {len(england_all):,}")
print(f"Total trusts (unique codes): {england_all['trust_code'].nunique()}")
print(f"Date range: {england_all['period'].min().strftime('%Y-%m')} to {england_all['period'].max().strftime('%Y-%m')}")
print(f"Unique periods: {england_all['period'].nunique()}")
print(f"\nNational headline metrics (averaged across all 86 months):")
print(f"  Average Type 1 4-hour %: {england_all['pct_4hr_type1'].mean():.1%}")
print(f"  Total Type 1 attendances (all periods): {england_all['attendances_type1'].sum():,.0f}")
print(f"  Total 12-hour waits (all periods): {england_all['waits_12hr'].sum():,.0f}")

Total rows: 10,736
Total trusts (unique codes): 136
Date range: 2019-04 to 2026-05
Unique periods: 86

National headline metrics (averaged across all 86 months):
  Average Type 1 4-hour %: 65.6%
  Total Type 1 attendances (all periods): 113,773,273
  Total 12-hour waits (all periods): 2,175,931

In [156]:
england_all.to_csv("data/processed/england_ae_2019_to_2026.csv", index=False)
print(f"Saved {len(england_all):,} rows to data/processed/england_ae_2019_to_2026.csv")

Saved 10,736 rows to data/processed/england_ae_2019_to_2026.csv

In [4]:
from pathlib import Path
Path("data/processed").mkdir(parents=True, exist_ok=True)

In [3]:
england =  pd.read_csv("data/processed/england_ae_2019_to_2026.csv")

In [159]:
england.head(5)

,trust_code,trust_region,trust_name,attendances_type1,breaches_4hr_type1,pct_4hr_type1,waits_12hr,admissions_type1,total_admissions,period
0,RDD,NHS England East Of England,Basildon And Thurrock University Hospitals NHS...,11354.0,811.0,0.928571,0.0,3098.0,3360.0,2019-04-01
1,RC1,NHS England East Of England,Bedford Hospital NHS Trust,6349.0,1334.0,0.789888,0.0,2069.0,2328.0,2019-04-01
2,RGT,NHS England East Of England,Cambridge University Hospitals NHS Foundation ...,10412.0,2520.0,0.757972,0.0,3426.0,4013.0,2019-04-01
3,RWH,NHS England East Of England,East And North Hertfordshire NHS Trust,9167.0,2590.0,0.717465,0.0,2928.0,3741.0,2019-04-01
4,RDE,NHS England East Of England,East Suffolk And North Essex NHS Foundation Trust,16818.0,2347.0,0.860447,1.0,4837.0,6630.0,2019-04-01